### ISSUE TITLE
怎么登陆系统？

### ISSUE THREAD

**Issue by joshle** [sxlfzhy/react-koa-demo#1]
没有注册用户的地方，也不知道怎么数据库 migration

**Comment by sxlfzhy** [comment]
是这个样子的，需要您自己在本地创建数据库，然后创建用户去登录

**Comment by sxlfzhy** [comment]
或者，您可以等到最晚周日晚上，我会更新一个版本，写更详细的文档，提供公共数据库供使用。最后谢谢您的关注，希望这个项目能帮助您

**Comment by sxlfzhy** [comment]
代码已经更新，你可以不必连接数据库，直接使用admin/admin进行登录

**Comment by grey5900** [comment]
@sxlfzhy hello，请问一下。npm run dev 启动后，登录admin/admin 请求报504,server没起起来吗？npm start 起不起来
